// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID        int32            `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Amount    string           `json:"amount"`
	Reason    *string          `json:"reason"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Type      *string          `json:"type"`
}

type User struct {
	ID       pgtype.UUID    `json:"id"`
	Username string         `json:"username"`
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Balance  pgtype.Numeric `json:"balance"`
}
